SET MY_USER = CURRENT_USER();

-- Roles
CREATE ROLE IF NOT EXISTS DEMO_ROLE;
GRANT ROLE DEMO_ROLE TO ROLE SYSADMIN;
GRANT ROLE DEMO_ROLE TO USER IDENTIFIER($MY_USER);

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS DEMO_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE DEMO_WH TO ROLE DEMO_ROLE;

-- Databases
CREATE DATABASE IF NOT EXISTS DEMO_DB;
GRANT OWNERSHIP ON DATABASE DEMO_DB TO ROLE DEMO_ROLE;

-- Schema
CREATE SCHEMA IF NOT EXISTS DEMO_DB.TPCH_TRANSFORMED;
GRANT OWNERSHIP ON SCHEMA DEMO_DB.TPCH_TRANSFORMED TO ROLE DEMO_ROLE;

ALTER USER MSHUKLASFC MODIFY PROGRAMMATIC ACCESS TOKEN DEMO_PAT
  SET MINS_TO_BYPASS_NETWORK_POLICY_REQUIREMENT = 60;
